# Generated by Django 5.2.3 on 2025-09-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('climate', models.CharField(default='Unknown')),
                ('diameter', models.IntegerField(default=0)),
                ('orbital_period', models.IntegerField(default=0)),
                ('population', models.BigIntegerField(default=0)),
                ('rotation_period', models.IntegerField(default=0)),
                ('surface_water', models.FloatField(default=0)),
                ('terrain', models.CharField(default='Unknown')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('birth_year', models.CharField(default='Unknown', max_length=32)),
                ('gender', models.CharField(default='Unknown', max_length=32)),
                ('eye_color', models.CharField(default='Unknown', max_length=32)),
                ('hair_color', models.CharField(default='Unknown', max_length=32)),
                ('height', models.IntegerField(default=0)),
                ('mass', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='ex09.planets')),
            ],
        ),
    ]
