# Generated by Django 5.2.3 on 2025-09-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
    ]
