# Generated by Django 5.2.3 on 2025-09-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_auto_20250910_1604'),
    ]

    operations = [
    ]
