# Generated by Django 5.2.3 on 2025-09-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_auto_20250910_1610'),
    ]

    operations = [
    ]
