# Generated by Django 5.2.3 on 2025-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0006_alter_planets_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(default=0, null=True),
        ),
    ]
