# Generated by Django 5.2.3 on 2025-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0008_alter_people_birth_year_alter_people_eye_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(default='Unknown', null=True),
        ),
    ]
