# Generated by Django 5.2.3 on 2025-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0002_alter_movies_episode_nb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(blank=True, default='Unknown', null=True),
        ),
    ]
