# Generated by Django 5.2.3 on 2025-09-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('birth_year', models.CharField(default='Unknown', max_length=32, null=True)),
                ('gender', models.CharField(default='Unknown', max_length=32)),
                ('eye_color', models.CharField(default='Unknown', max_length=32, null=True)),
                ('hair_color', models.CharField(default='Unknown', max_length=32, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
                ('mass', models.FloatField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('climate', models.CharField(default='Unknown', null=True)),
                ('diameter', models.IntegerField(default=0, null=True)),
                ('orbital_period', models.IntegerField(default=0, null=True)),
                ('population', models.BigIntegerField(default=0, null=True)),
                ('rotation_period', models.IntegerField(default=0, null=True)),
                ('surface_water', models.FloatField(default=0, null=True)),
                ('terrain', models.CharField(default='Unknown', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('episode_nb', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(blank=True, default='Unknown', null=True)),
                ('director', models.CharField(default='Unknown', max_length=32)),
                ('producer', models.CharField(default='Unknown', max_length=128)),
                ('release_date', models.DateField(default='27-08-2025')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='resident', to='ex10.people')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='ex10.planets'),
        ),
    ]
