# Generated by Django 5.2.3 on 2025-09-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='updated',
        ),
    ]
