# Generated by Django 5.2.3 on 2025-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('title', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('episode_nb', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(default='Unknown', null=True)),
                ('director', models.CharField(default='Unknown', max_length=32)),
                ('producer', models.CharField(default='Unknown', max_length=128)),
                ('release_date', models.DateField(default='27-08-2025')),
            ],
        ),
    ]
