# Generated by Django 5.2.3 on 2025-08-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
