
version: "3.9"

services:
  postgresql:
    container_name: postgre
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d formationdjango"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: formationdjango
    volumes:
     - postgre_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"


  django:
    build:
      context: .
      dockerfile: ./requirements/django/Dockerfile
    container_name: django_app
    command: python /d42/d42/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/d42
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - DB_NAME=formationdjango
      - DB_USER=djangouser
      - DB_PASSWORD=secret
      - DB_HOST=postgresql
      - DB_PORT=5432
    
volumes:
  postgre_data:
    