# Generated by Django 5.2.3 on 2025-09-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_auto_20250910_1615'),
    ]

    operations = [
    ]
