# Generated by Django 5.2.3 on 2025-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_auto_20250910_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
