# Generated by Django 5.2.3 on 2025-09-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0007_alter_planets_surface_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_year',
            field=models.CharField(default='Unknown', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(default='Unknown', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(default='Unknown', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
