# Generated by Django 5.2.3 on 2025-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0009_alter_planets_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(default='Unknown', null=True),
        ),
    ]
