# Generated by Django 5.2.3 on 2025-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('episode_nb', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(blank=True, default='Unknown', null=True)),
                ('director', models.CharField(default='Unknown', max_length=32)),
                ('producer', models.CharField(default='Unknown', max_length=128)),
                ('release_date', models.DateField(default='27-08-2025')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
