# Generated by Django 5.2.3 on 2025-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex07', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
