# Generated by Django 5.2.9 on 2026-02-12 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('author', models.CharField(max_length=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('down_vote', models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL)),
                ('up_vote', models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
